services:
  db:
    container_name: postgres-14.18
    image: postgres:14.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5433:5432'


  adminer:
    container_name: adminer-5.3.0-standalone
    image: adminer:5.3.0-standalone
    restart: always
    ports:
      - '9081:8080'

  smtp4dev:
    image: rnwood/smtp4dev:prerelease
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'